### ISSUE TITLE
Additional types of exchange in rabbitmq.

### ISSUE THREAD

**Issue by Derfirm** [mosquito/crew#24]
Greetings!
I really like this library , I would like to say thank you.
But sometimes is a need to send a particular task a worker (direct type) or all at once (fanout), perhaps you have an idea how to implement it, or better yet, ready examples?

**Comment by mosquito** [comment]
Yes. I had an idea about fanout (actually about PUP/SUB). I already implemented this behaviour in another library. But this library is closed now.

**Comment by Derfirm** [comment]
Sadly.
Can You provide link on another library?

**Comment by ei-grad** [comment]
He wants to say that this behaviour is implemented in another library which is not yet opensourced. Crew is not closed :-).

**Comment by mosquito** [comment]
You can use publish/subscribe methods from master-client.
https://github.com/mosquito/crew/blob/master/crew/master/tornado/client.py#L230-L243
https://github.com/mosquito/crew/blob/master/crew/master/tornado/client.py#L212-L214

But worker-client suport is only publishing
https://github.com/mosquito/crew/blob/master/crew/worker/pubsub.py#L34-L45

This limitation is due to the client architecture.

**Comment by Derfirm** [comment]
Oh, that's great:)
Thank you for your answers, will follow for updates
